### ISSUE TITLE
Could libngapcodec support new release?

### ISSUE THREAD

**Issue by hyrut** [FredericLeroy/libngapcodec#1]
Hi, Dear Frederic:
    Here is a user of your libngapcodec.
    And I want to decode some ngap binary by using your libngapcodec.
    But I found two issues:
    1. I am using a ubuntu 18 system, after install asn1c by command "apt install ans1c", ans1c  v0.9.28 was installed, but when I call the script "generate_src_from_asn.1.sh", looks the option "-D" is not available. I got error message "asn1c: invalid option -- 'D'". This option is removed in version 0.9.28. And with asn.1 0.9.28, I could compile the 38.413 15.3.0 even.
    2. when I call the update_3gpp_spec_ts38413.py, I got some error as following.
root@ubuntu18-1:~/libngapcodec/oai-libngapcodec-master# python ./scripts/update_3gpp_spec_ts38413.py -v 16.1.0 -o asn.1 38413
downloading ftp://ftp.3gpp.org/Specs/archive/38_series/38.413/38413-g10.zip
unarchive zip
found document : 38413-g10.doc
converting document to text using soffice --headless --cat /tmp/tmp2kYamC.doc
Traceback (most recent call last):
  File "./scripts/update_3gpp_spec_ts38413.py", line 276, in <module>
    main()
  File "./scripts/update_3gpp_spec_ts38413.py", line 273, in main
    ts3gpp.convert_ts_to_asn1(version, args.output_directory)
  File "./scripts/update_3gpp_spec_ts38413.py", line 224, in convert_ts_to_asn1
    ts_as_text = Ts3gpp.unzip_and_convert_to_text(zipcontent)
  File "./scripts/update_3gpp_spec_ts38413.py", line 176, in unzip_and_convert_to_text
    text = subprocess.check_output(command.split(" "))
  File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Actually, I want to update to 16.1.0 for the 38.413.
I think this lib need update some scripts for support this.

**Comment by hyrut** [comment]
Do you have any update plan for this?
Really like this lib since I am working on 5G system.

**Comment by hyrut** [comment]
sorry, I donot install the asn1c s1ap fork and office lib according to your instruction. Will try it and come back again.

**Comment by hyrut** [comment]
After applying the absence steps, I stopped at compiling the src folder source.
root@ubuntu18-1:/work/libngap/oai-libngapcodec-master# make
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_Criticality.o -c src/Ngap_Criticality.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_Presence.o -c src/Ngap_Presence.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_PrivateIE-ID.o -c src/Ngap_PrivateIE-ID.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProcedureCode.o -c src/Ngap_ProcedureCode.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolExtensionID.o -c src/Ngap_ProtocolExtensionID.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-ID.o -c src/Ngap_ProtocolIE-ID.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_TriggeringMessage.o -c src/Ngap_TriggeringMessage.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-Container.o -c src/Ngap_ProtocolIE-Container.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-SingleContainer.o -c src/Ngap_ProtocolIE-SingleContainer.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-Field.o -c src/Ngap_ProtocolIE-Field.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-ContainerPair.o -c src/Ngap_ProtocolIE-ContainerPair.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-FieldPair.o -c src/Ngap_ProtocolIE-FieldPair.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-ContainerList.o -c src/Ngap_ProtocolIE-ContainerList.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolIE-ContainerPairList.o -c src/Ngap_ProtocolIE-ContainerPairList.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolExtensionContainer.o -c src/Ngap_ProtocolExtensionContainer.c
cc  -DASN_PDU_COLLECTION -I. -Iinclude/asn1c -o src/Ngap_ProtocolExtensionField.o -c src/Ngap_ProtocolExtensionField.c
src/Ngap_ProtocolExtensionField.c:25223:6: error: ‘asn_OER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’ undeclared here (not in a function); did you mean ‘memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368’?
   { &asn_OER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6, &asn_PER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6,  memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368
src/Ngap_ProtocolExtensionField.c:25223:102: error: ‘asn_PER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’ undeclared here (not in a function); did you mean ‘asn_OER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6’?
   { &asn_OER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6, &asn_PER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6,  memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constraint_368 },
                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                      asn_OER_memb_Ngap_OCTET_STRING_CONTAINING_PDUSessionResourceReleaseResponseTransfer__constr_6

Even I try to compile the 15.3.0 version, i got same issue.
I have checked the code, the code of my 15.3.0 is different from 15.3.0 you compiled, even asn1c are both 0.9.29, and the fork is s1ap.
I will check the asn1c again, and will come back if any update.
